### ISSUE TITLE
conda problem?

### ISSUE THREAD

**Issue by wwood** [rhysnewell/BinSnek#1]
Hey,

Running into this, after creating a new conda env from scratch

```
(/home/woodcrob/e/binsnek-dev) lyra04:20201114:~/m/msingle-tmp-ben/mess/45_r95_on_wierd_L11/possible_finds/BinSnek$ snakemake --use-conda --cores 128 recover_mags
Building DAG of jobs...
Creating conda environment envs/maxbin2.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /work2/microbiome/msingle-tmp-ben/mess/45_r95_on_wierd_L11/possible_finds/BinSnek/envs/maxbin2.yaml:
Collecting package metadata (repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/woodcrob/e/binsnek-dev/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 107, in touch
        mkdir_p_sudo_safe(dirpath)
      File "/home/woodcrob/e/binsnek-dev/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
        os.mkdir(path)
    FileExistsError: [Errno 17] File exists: '/home/woodcrob/e/binsnek-dev/pkgs'

    During handling of the above exception, another exception occurred:
...
```
Any ideas?
Thanks.

**Comment by rhysnewell** [comment]
Hi,
Yeah, this is a random conda issue. I've come across it previously, but got around it by just deleting the offending file in `pkgs` and then trying again.

Rhys

**Comment by rhysnewell** [comment]
Would you be willing to retry this with this updated version of binsnek? It uses a different version snakemake and is also just generally easier to use. It's packaged as a command line tool rather than a snakemake pipeline now
